# =========== test ===========
set(PROJECT_TEST_BAS_DIR ${CMAKE_CURRENT_LIST_DIR})
set(PROJECT_TEST_SRC_DIR ${PROJECT_TEST_BAS_DIR})
set(PROJECT_TEST_INC_DIR ${PROJECT_TEST_BAS_DIR})

include("${ATFRAMEWORK_ATFRAME_UTILS_REPO_DIR}/test/test.utils-macro.cmake")
